### ISSUE TITLE
Decrease bundle size

### ISSUE THREAD

**Issue by tonyketcham** [tonyketcham/p5-svelte#4]
Other p5 wrappers on npm have remarkably small unpacked bundle sizes. Currently, with p5-svelte the entire p5 minified library is being bundled into the `index.js` file by Rollup.

I would think just keeping p5 as a peer dependency would work. However, perhaps CommonJS from `@rollup/plugin-commonjs` is what is bundling the library.

When I try building p5-svelte without CommonJS, the build fails with an error:
```bash
src/index.js → dist/index.mjs, dist/index.js...
[!] Error: 'default' is not exported by node_modules/p5/lib/p5.min.js, imported by src/p5/action.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/p5/action.js (1:7)
1: import p5 from 'p5';
          ^
2: 
3: export default function _p5(node, workspace) {
Error: 'default' is not exported by node_modules/p5/lib/p5.min.js, imported by src/p5/action.js
    at error (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at Module.error (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:9858:16)
    at handleMissingExport (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:9747:28)
    at Module.traceVariable (p5-svelte/node_modules/rollup/dist/shared/rollup.js:10251:24)
    at ModuleScope.findVariable (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:8770:39)
    at FunctionScope.findVariable (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:2782:38)
    at ChildScope.findVariable (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:2782:38)
    at Identifier$1.bind (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:4138:40)
    at NewExpression.bind (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:2868:23)
    at NewExpression.bind (/p5-svelte/node_modules/rollup/dist/shared/rollup.js:8035:15)

npm ERR! code 1
npm ERR! path /p5-svelte
npm ERR! command failed
npm ERR! command sh -c rollup -c
```

**Comment by tonyketcham** [comment]
### Status
Solved in release [v2.2.1](https://github.com/tonyketcham/p5-svelte/releases/tag/v2.2.1).

### Solution 
Reduce bundle size by explicitly removing p5 from bundle 26f3356

Implemented `rollup-plugin-includepaths` in place of `@rollup/plugin-commonjs` in the Rollup config to be able to declare that p5 not be included in the final bundle.
